### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [16]:
import numpy as np

a = np.random.randint(1,100,15)
print(a)

print(np.sort(a))
print(np.sort(a)[::-1]) # descending order

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]
[24 30 32 45 52 52 52 53 56 58 71 76 82 94 99]
[99 94 82 76 71 58 56 53 52 52 52 45 32 30 24]


In [14]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

print(np.sort(b,axis=1)) # row-wise sort [each row is sorted] (DEFAULT CASE) 
print(np.sort(b,axis=0)) # column-wise sort [each col is sorted]

[[15 29 31 36]
 [32 98 62 89]
 [27 34 72 46]
 [84 47 65 87]
 [54 59 54 74]
 [24 52 82 88]]
[[15 29 31 36]
 [32 62 89 98]
 [27 34 46 72]
 [47 65 84 87]
 [54 54 59 74]
 [24 52 82 88]]
[[15 29 31 36]
 [24 34 54 46]
 [27 47 62 74]
 [32 52 65 87]
 [54 59 72 88]
 [84 98 82 89]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [24]:
# 1D array

print(a)
np.append(a,200)

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]


array([ 58,  71,  53,  99,  82,  52,  45,  52,  30,  56,  52,  94,  32,
        24,  76, 200])

In [42]:
# 2D array

print(b)
print(np.append(b,np.ones((b.shape[0],1)))) # by default it converted 2D to 1D, then added items
print(np.append(b,np.ones((b.shape[0],1)),axis=1)) # to add col, we need to mention axis = 1
print(np.append(b,np.ones((1,b.shape[1])),axis=0)) # to add row, we need to mention axis = 0

[[15 29 31 36]
 [32 98 62 89]
 [27 34 72 46]
 [84 47 65 87]
 [54 59 54 74]
 [24 52 82 88]]
[15. 29. 31. 36. 32. 98. 62. 89. 27. 34. 72. 46. 84. 47. 65. 87. 54. 59.
 54. 74. 24. 52. 82. 88.  1.  1.  1.  1.  1.  1.]
[[15. 29. 31. 36.  1.]
 [32. 98. 62. 89.  1.]
 [27. 34. 72. 46.  1.]
 [84. 47. 65. 87.  1.]
 [54. 59. 54. 74.  1.]
 [24. 52. 82. 88.  1.]]
[[15. 29. 31. 36.]
 [32. 98. 62. 89.]
 [27. 34. 72. 46.]
 [84. 47. 65. 87.]
 [54. 59. 54. 74.]
 [24. 52. 82. 88.]
 [ 1.  1.  1.  1.]]


### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis. (majorly used with tabular data)

can be used in replacement of stacking

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [47]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [68]:
np.concatenate((c,d),axis=0) # row-wise (no. of rows increases)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
np.concatenate((c,d),axis=1) # col-wise (no. of cols increases)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [54]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

print(e)
print(np.unique(e))

[1 1 2 2 3 3 4 4 5 5 6 6]
[1 2 3 4 5 6]


### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [58]:
print(a)
a.shape

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]


(15,)

In [72]:
print(np.expand_dims(a,axis=0)) # row-wise (no. of rows remains same)
np.expand_dims(a,axis=0).shape

[[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]]


(1, 15)

In [74]:
print(np.expand_dims(a,axis=1)) # col-wise (no. of cols remains same)
np.expand_dims(a,axis=1).shape

[[58]
 [71]
 [53]
 [99]
 [82]
 [52]
 [45]
 [52]
 [30]
 [56]
 [52]
 [94]
 [32]
 [24]
 [76]]


(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [80]:
print(a)

# Way-1: np.where(condition)
print(np.where(a>50)) # find all indices with value greater than 50

# Way-2: np.where(condition,true, false)
print(np.where(a>50,0,a)) # replace all values > 50 with 0
print(np.where(a%2 == 0,0,a))

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]
(array([ 0,  1,  2,  3,  4,  5,  7,  9, 10, 11, 14]),)
[ 0  0  0  0  0  0 45  0 30  0  0  0 32 24  0]
[ 0 71 53 99  0  0 45  0  0  0  0  0  0  0  0]


### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [92]:
print(a)

print(np.argmax(a))
print(np.argmin(a))

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]
3
13


In [90]:
print(b)

print(np.argmax(b,axis=0)) # col-wise max
print(np.argmax(b,axis=1)) # row-wise max

[[15 29 31 36]
 [32 98 62 89]
 [27 34 72 46]
 [84 47 65 87]
 [54 59 54 74]
 [24 52 82 88]]
[3 1 5 1]
[3 1 2 3 3 3]


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [95]:
print(a)

print(np.cumsum(a))

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]
[ 58 129 182 281 363 415 460 512 542 598 650 744 776 800 876]


In [97]:
print(b)

print(np.cumsum(b,axis=1))
print(np.cumsum(b)) # converted to 1D, then applied cumsum

[[15 29 31 36]
 [32 98 62 89]
 [27 34 72 46]
 [84 47 65 87]
 [54 59 54 74]
 [24 52 82 88]]
[[ 15  44  75 111]
 [ 32 130 192 281]
 [ 27  61 133 179]
 [ 84 131 196 283]
 [ 54 113 167 241]
 [ 24  76 158 246]]
[  15   44   75  111  143  241  303  392  419  453  525  571  655  702
  767  854  908  967 1021 1095 1119 1171 1253 1341]


In [101]:
# np.cumprod
print(a)

print(np.cumprod(a))

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]
[                  58                 4118               218254
             21607146           1771785972          92132870544
        4145979174480      215590917072960     6467727512188800
   362192740682572800   387278441784233984  -489314619701108736
  2788676243274072064 -6858746456260476928 -4755896611928801280]


### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

$P = (\frac{n}{N})\times 100$

where,
<br>P --> percentile
<br>n --> number of values below 'x'
<br>N --> total count of population

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [111]:
# x percentile means x% of total population are behind the current candidate
print(a)

print(np.percentile(a,100)) # max number
print(np.percentile(a,0)) # min number
print(np.percentile(a,50)) # median

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]
99.0
24.0
53.0


In [113]:
np.median(a)

53.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [124]:
print(a)

np.histogram(a,bins=[0,50,100])

[58 71 53 99 82 52 45 52 30 56 52 94 32 24 76]


(array([ 4, 11]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [128]:
# correlation coefficient lies in range [-1,1]

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience) # correlation of any quantity with itself is always 1

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [170]:
a = np.array([11,53,28,50,38,37,94,92,5,30,68,9,78,2,21])
print(a)

items = [10,20,30,40,50,60,70,80,90,100]
print(np.isin(a,items))
print(a[np.isin(a,items)]) # Boolean masking: tells which values are present

[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]
[False False False  True False False False False False  True False False
 False False False]
[50 30]


### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [156]:
print(a)

print(np.flip(a))

[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]
[21  2 78  9 68 30  5 92 94 37 38 50 28 53 11]


In [162]:
print(b)

print(np.flip(b)) # row & col flip, both happened
print(np.flip(b,axis=1)) # col flip only

[[15 29 31 36]
 [32 98 62 89]
 [27 34 72 46]
 [84 47 65 87]
 [54 59 54 74]
 [24 52 82 88]]
[[88 82 52 24]
 [74 54 59 54]
 [87 65 47 84]
 [46 72 34 27]
 [89 62 98 32]
 [36 31 29 15]]
[[36 31 29 15]
 [89 62 98 32]
 [46 72 34 27]
 [87 65 47 84]
 [74 54 59 54]
 [88 82 52 24]]


### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [172]:
print(a)

np.put(a,[0,1],[110,530]) # [0,1] are indexes you want to replace 
print(a) # NOTE: numpy.put() does PERMANENT changes

[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]
[110 530  28  50  38  37  94  92   5  30  68   9  78   2  21]


### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [180]:
print(a)

np.delete(a,[0,2,4]) # 0,2,4 are indexes
# NOTE: numpy.delete() does TEMPORARY changes

[110 530  28  50  38  37  94  92   5  30  68   9  78   2  21]


array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [198]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

print(np.union1d(m,n))
print(np.intersect1d(m,n))
print(np.setdiff1d(m,n)) # m-n
print(np.setdiff1d(n,m)) # n-m
print(np.setxor1d(m,n)) # all elements where aren't present in both (remove common ones, rest keep everything)

print(np.in1d(m,[1,3])) # returns boolean array of size same as m, true where elements of m are present in [1,3]
m[np.in1d(m,[1,3])] # boolean masking

[1 2 3 4 5 6 7]
[3 4 5]
[1 2]
[6 7]
[1 2 6 7]
[ True False  True False False]


array([1, 3])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [202]:
print(a)

np.clip(a,a_min=25,a_max=75) # higher values are replaced with a_max & lower values with a_min

[110 530  28  50  38  37  94  92   5  30  68   9  78   2  21]


array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

### Below functions to be done at time of Interview Preparation

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals